# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy project files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (most likely not needed for stdio based MCP, but can be added)

CMD [ "node", "build/index.js" ]
